service uhci_hcd
{
	system
		PRIVCTL		#  4
		UMAP		# 14
		IRQCTL		# 19
		DEVIO		# 21
		;
	pci device	0c/03/00;	# USB UHCI controller
	ipc
		SYSTEM pm rs log tty ds vfs vm pci
		usb_core
		;
	uid	0;
};
